package main

import (
	"fmt"
	"regexp"
	"strings"
)

// anchorEntry maps a user-defined anchor id to the chapter file it lives in.
type anchorEntry struct {
	chapterFile string
}

// indexEntry records one occurrence of an index term in the text.
type indexEntry struct {
	displayTerm string // text shown in the running text
	canonical   string // key used for grouping in the index (defaults to displayTerm)
	indexName   string
	chapterFile string
	htmlID      string
}

// tocEntry records one heading for the %toc command.
type tocEntry struct {
	level       int    // 1 for chapters (h1), 2-6 for subchapters
	title       string // raw markdown title, inline-parsed at render time
	chapterFile string // file the heading lives in
	label       string // heading anchor id (label<level>_<n>)
}

var (
	// anchors maps anchor id → chapter file (populated by scanAnchorsAndIndex)
	anchors = map[string]anchorEntry{}

	// indexes maps index name → ordered list of occurrences
	indexes = map[string][]indexEntry{}

	// indexCounters tracks how many times each (indexName+term) combo has been seen
	// during Pass 2 rendering so we can assign stable sequential IDs
	indexCounters = map[string]int{}

	// tocEntries lists all headings in document order (populated by scanAnchorsAndIndex)
	tocEntries []tocEntry

	// footnoteDefs maps a footnote id to its (raw markdown) definition text,
	// collected in Pass 1 so a reference may appear before its definition.
	footnoteDefs = map[string]string{}

	// Per-chapter footnote state, reset whenever a chapter is finalized.
	footnoteNum      int            // last number assigned in the current chapter
	footnoteAssigned = map[string]int{}
	pendingFootnotes []pendingNote
)

// pendingNote is a footnote referenced in the current chapter and awaiting
// emission as an <aside> when the chapter is finalized.
type pendingNote struct {
	chap int    // chapter number (for globally unique ids)
	num  int    // display number within the chapter
	id   string // author-supplied footnote id
}

var (
	reAnchorDef   = regexp.MustCompile(`\{#([a-zA-Z0-9_-]+)\}`)
	reAnchorLink  = regexp.MustCompile(`\[([^\]]+)\]\(#([a-zA-Z0-9_-]+)\)`)
	// %[displayTerm](indexname) or %[displayTerm](indexname|canonical)
	reIndexEntry = regexp.MustCompile(`%\[([^\]]+)\]\(([^)|]+)(?:\|([^)]+))?\)`)
	// %index[name] or %index[name](Title)
	reIndexOutput = regexp.MustCompile(`^%index\[([^\]]+)\](?:\(([^)]+)\))?$`)
	// %toc or %toc(Title)
	reTocOutput = regexp.MustCompile(`^%toc(?:\(([^)]+)\))?$`)
	// [^id]: definition text  (a footnote definition line)
	reFootnoteDef = regexp.MustCompile(`^\s*\[\^([a-zA-Z0-9_-]+)\]:\s*(.*)$`)
	// [^id]  (an inline footnote reference)
	reFootnoteRef = regexp.MustCompile(`\[\^([a-zA-Z0-9_-]+)\]`)
)

// resetAnchors clears all anchor/index state so processMarkdownFile is idempotent.
func resetAnchors() {
	anchors = map[string]anchorEntry{}
	indexes = map[string][]indexEntry{}
	indexCounters = map[string]int{}
	tocEntries = nil
	footnoteDefs = map[string]string{}
	footnoteNum = 0
	footnoteAssigned = map[string]int{}
	pendingFootnotes = nil
}

// chapterFileForNumber returns the deterministic XHTML filename for a chapter number.
func chapterFileForNumber(n int) string {
	return fmt.Sprintf("xhtml/chapter_%05d.xhtml", n)
}

// scanAnchorsAndIndex performs Pass 1: walks all lines of the fully-included
// content, tracks chapter numbering exactly as Pass 2 rendering does
// (including the chapters generated by %toc and non-empty %index commands),
// and populates the anchors, indexes and tocEntries collections.
func scanAnchorsAndIndex(content string) {
	lines := reNewline.Split(content, -1)

	// Sub-pass A: count entries per index name, so we know which %index
	// commands will produce a chapter (empty indexes are skipped in Pass 2).
	indexEntryCount := map[string]int{}
	for _, line := range lines {
		for _, m := range reIndexEntry.FindAllStringSubmatch(line, -1) {
			indexEntryCount[m[2]]++
		}
	}

	// Sub-pass B: mirror Pass 2 chapter numbering and collect everything.
	// levelNum mirrors currentChapterNumber: index 1 counts chapters (h1,
	// %toc, non-empty %index), indices 2-6 count subchapter headings.
	var levelNum [7]int
	for _, line := range lines {
		switch {
		case reChapter.MatchString(line):
			m := reChapter.FindStringSubmatch(line)
			levelNum[1]++
			tocEntries = append(tocEntries, tocEntry{
				level:       1,
				title:       m[2],
				chapterFile: chapterFileForNumber(levelNum[1]),
				label:       fmt.Sprintf("label1_%d", levelNum[1]),
			})
		case reHeadlines.MatchString(line):
			m := reHeadlines.FindStringSubmatch(line)
			level := strings.Count(m[1], "#")
			levelNum[level]++
			if levelNum[1] > 0 { // headings before the first chapter have no file
				tocEntries = append(tocEntries, tocEntry{
					level:       level,
					title:       m[2],
					chapterFile: chapterFileForNumber(levelNum[1]),
					label:       fmt.Sprintf("label%d_%d", level, levelNum[level]),
				})
			}
		case reTocOutput.MatchString(line):
			levelNum[1]++ // the TOC chapter itself; not listed as an entry
		case reIndexOutput.MatchString(line):
			m := reIndexOutput.FindStringSubmatch(line)
			if indexEntryCount[m[1]] > 0 {
				levelNum[1]++
				title := m[2]
				if title == "" {
					title = m[1]
				}
				tocEntries = append(tocEntries, tocEntry{
					level:       1,
					title:       title,
					chapterFile: chapterFileForNumber(levelNum[1]),
					label:       fmt.Sprintf("label1_%d", levelNum[1]),
				})
			}
		}

		currentFile := chapterFileForNumber(levelNum[1])

		// Collect [^id]: footnote definitions (so a reference may precede its
		// definition). A definition line yields no inline output in Pass 2.
		if m := reFootnoteDef.FindStringSubmatch(line); m != nil {
			if _, exists := footnoteDefs[m[1]]; exists {
				logMsg(LogDefault, "WARNING: duplicate footnote id %q (second definition ignored)", m[1])
			} else {
				footnoteDefs[m[1]] = m[2]
				logMsg(LogVerbose, "Footnote %q registered", m[1])
			}
			continue
		}

		// Collect {#id} anchor definitions.
		for _, m := range reAnchorDef.FindAllStringSubmatch(line, -1) {
			id := m[1]
			if _, exists := anchors[id]; exists {
				logMsg(LogDefault, "WARNING: duplicate anchor id %q (second occurrence in %s ignored)", id, currentFile)
				continue
			}
			anchors[id] = anchorEntry{chapterFile: currentFile}
			logMsg(LogVerbose, "Anchor %q registered in %s", id, currentFile)
		}

		// Collect %[displayTerm](indexname) or %[displayTerm](indexname|canonical) entries.
		for _, m := range reIndexEntry.FindAllStringSubmatch(line, -1) {
			displayTerm, indexName, canonical := m[1], m[2], m[3]
			if canonical == "" {
				canonical = displayTerm
			}
			key := indexName + "\x00" + canonical
			seq := indexCounters[key]
			indexCounters[key]++
			htmlID := fmt.Sprintf("idx-%s-%s-%d", sanitizeID(indexName), sanitizeID(canonical), seq)
			indexes[indexName] = append(indexes[indexName], indexEntry{
				displayTerm: displayTerm,
				canonical:   canonical,
				indexName:   indexName,
				chapterFile: currentFile,
				htmlID:      htmlID,
			})
			logMsg(LogVerbose, "Index entry %q → %q (%s) registered as %s in %s", displayTerm, canonical, indexName, htmlID, currentFile)
		}
	}

	// Reset counters; Pass 2 rendering uses the same deterministic formula.
	indexCounters = map[string]int{}
}

// sanitizeID converts a string to a safe HTML id fragment.
func sanitizeID(s string) string {
	s = strings.ToLower(s)
	var b strings.Builder
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		} else {
			b.WriteRune('-')
		}
	}
	return strings.Trim(b.String(), "-")
}

// resolveAnchorHref returns the href value for a link to anchorID from currentChapterFile.
// In AZW3 mode all chapters form one concatenated document, so all links are plain #id.
func resolveAnchorHref(ctx *parseContext, anchorID, currentChapterFile string) string {
	entry, ok := anchors[anchorID]
	if !ok {
		logMsg(LogDefault, "WARNING: anchor %q not found", anchorID)
		return "#" + anchorID
	}
	if ctx.azw3Mode || entry.chapterFile == currentChapterFile {
		return "#" + anchorID
	}
	return "../" + entry.chapterFile + "#" + anchorID
}
